version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
    - 80:80
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
  code-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME:-workshop-user-env-master}
    runtime: sysbox-runc
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=US/Eastern
    - PASSWORD=workshop
    - SUDO_PASSWORD=root
    - VIRTUAL_HOST=user0.quokka.ninja
    - VIRTUAL_PORT=8443
    volumes:
    - $HOME/devops-workshop/data/userdata/user0/config:/config
    expose:
    - 8443
    restart: unless-stopped
  gitea:
    image: gitea/gitea
    container_name: gitea
    runtime: sysbox-runc
    environment:
    - USER_UID=1100
    - USER_GID=1100
    - VIRTUAL_HOST=git.quokka.ninja
    - VIRTUAL_PORT=3000
    volumes:
    - $HOME/devops-workshop/data/appdata/gitea:/data
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    ports:
    - '2222:22'
    expose:
    - 3000
    restart: unless-stopped
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    runtime: sysbox-runc
    privileged: true
    user: root
    environment:
    - VIRTUAL_HOST=jenkins.quokka.ninja
    - VIRTUAL_PORT=8080
    volumes:
    - $HOME/devops-workshop/data/appdata/jenkins:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    ports:
    - 50000:50000
    expose:
    - 8080
    restart: unless-stopped
networks:
  default:
    external:
      name: devops-workshop-net