version: "3"
services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    environment:
      - VIRTUAL_HOST=portainer.quokka.ninja
      - VIRTUAL_PORT=9000
    volumes:
      - ./portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
      # - 9000:9000
    expose:
      - 9000
    restart: unless-stopped
networks:
  default:
    external:
      name: devops-workshop-net
